<?php
namespace app\models;

use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;

/**
 * model of suppilers
 * Class Supplier
 * @package app\models
 */
class Supplier extends ActiveRecord
{

    public function rules()
    {
        $rules = [
   
            ['id','string','length' =>[1,100]],
            ['name','string','length' =>[1,50]],
            ['code','string','length' =>[1,3]],
            [['id','name','code', 't_status'] , 'safe']
        ];

        return $rules; // TODO: Change the autogenerated stub
    }


    public function search($params)
    {
        $query = self::find();
        $dataProvider = new ActiveDataProvider([ 'query' => $query,
                                                 'pagination' => ['pageSize' => 50]
                                               ]);

        if (!($this->load($params) && $this->validate())) {
            return $dataProvider;
        }

        $query = $this->getQueryByIdCondition($query, $this->id);
        $query->andFilterWhere(['=', "t_status", $this->t_status]);
        $query->andFilterWhere(['like', "name", $this->name]);
        $query->andFilterWhere(['like', "code", $this->code]);

        return $dataProvider;
    }


    /**
     * id 查询
     * @param $query
     * @param $id
     * @return mixed
     */
    private function getQueryByIdCondition($query, $id)
    {
        if ($id) {
            //纯数字 ，等值匹配
            preg_match("/^([1-9]\d*)$/", $id, $match);
            if (isset($match[1])) {
                $query->andFilterWhere(["=", "id", $match[1]]);
                return $query;
            }

            //处理 > < >= <=
            preg_match("/^([\>\<]\=?)\s*(\d+)$/", $id, $match);
            \Yii::info("getQueryByIdCondition:".json_encode($match), "debug");
            if (isset($match[1])) {
                   $query->andFilterWhere([$match[1], "id", $match[2]]);
                   return $query;
            }

            //处理范围  15-100
            preg_match("/^(\d+)\s*\-\s*(\d+)$/", $id, $match);
            if (isset($match[1]) && isset($match[2])) {
                $query->andFilterWhere([">=", "id", $match[1]]);
                $query->andFilterWhere(["<=", "id", $match[2]]);
                return $query;
            }
        }
        return $query ;
    }


}
